Spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;     #여러개가 한번에 접근할떄 빨리처리됨 권장임
    username: root
    password: root
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #자동으로 테이블 만들어줌
    properties: #hibernate 특정한걸 쓸수있음
      hibernate:
#        show_sql: true
        format_sql: true


logging:
  Level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace



